services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rainbump
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
     - '5435:5432'
  web:
    environment:
      - PORT=9240
      - HOST=0.0.0.0
    build:
      dockerfile: ./web/Dockerfile
      context: ./
    ports:
      - "9240:9240"
  backend:
    environment:
      - PORT=5055
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    ports:
      - "5055:5055"
